# Generated by Django 4.2.9 on 2026-01-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_suppliers_stockentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntryArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_entry_archive',
            },
        ),
    ]
