# Generated by Django 4.2.9 on 2026-01-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockEntryArchive',
        ),
    ]
